home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
]

tours/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_tours, name='tours'),
    path('<int:tour_id>/', views.indv_tour, name='indv_tour'),
    path('<int:tour_id>/make_review/', views.make_review,
         name='make_review'),
    path('<int:tour_id>/add_review/', views.add_review,
         name='add_review'),
    path('add/', views.add_tour, name='add_tour'),
    path('edit/<int:tour_id>', views.edit_tour, name='edit_tour'),
    path('delete/<int:tour_id>', views.delete_tour, name='delete_tour'),
    path('categories/', views.all_categories, name='categories'),
    path('categories/add_category/', views.add_category, name='add_category'),
    path('categories/edit_category/<int:category_id>',
         views.edit_category, name='edit_category'),
    path('categories/delete/<int:category_id>',
         views.delete_category, name='delete_category'),
]

tuktuk_tours/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('tours/', include('tours.urls')),
    path('basket/', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('blog/', include('blogs.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tours/models.py
from django.db import models

# Create your models here.


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'
    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=False, blank=False,
                                     default='')

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Tour(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True,
                                 on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    duration = models.DecimalField(max_digits=3, decimal_places=1, default=0)
    start_time = models.CharField(max_length=254, null=False, blank=False,
                                  default='')
    includes = models.TextField()
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

    def get_tour_name(self):
        return self.name


class Review(models.Model):
    tour = models.ForeignKey(Tour, null=False, blank=False,
                             on_delete=models.CASCADE,
                             related_name='reviews',)
    title = models.CharField(max_length=254, null=False, blank=True)
    author = models.CharField(max_length=50, null=False, blank=False,
                              default='')
    review_content = models.TextField()
    review_emoji = models.ForeignKey('Rating', null=False, blank=False,
                                     on_delete=models.CASCADE,
                                     related_name='reviews', default='')
    writtenon = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['writtenon']

    def __str__(self):
        return self.title


class Rating(models.Model):

    class Meta:
        verbose_name_plural = 'Ratings'
    rating_name = models.CharField(max_length=254, null=False, blank=False,
                                   default='')
    rating_number = models.IntegerField(null=False, blank=False, default=0)

    def __str__(self):
        return self.rating_name

    def get_rating_name(self):
        return self.rating_name

tours/forms.py
from django import forms
from .models import Tour, Category, Review, Rating


class TourDetailForm(forms.ModelForm):

    class Meta:
        model = Tour
        fields = ('name',
                  'category',
                  'sku',
                  'description',
                  'includes',
                  'price',
                  'duration',
                  'start_time',
                  'image_url',
                  'image',
                  )

    name = forms.CharField(label='Tour Name (e.g. Mojokerto Market Tour)')
    sku = forms.CharField(label='Create new sku (e.g. tt00025)')
    description = forms.CharField(label='Description (give details about '
                                  'what you will see or do, with '
                                  'some historical background)')
    price = forms.DecimalField(label='Price (e.g. $25.00)')
    duration = forms.DecimalField(label='Duration in hours (e.g. 2.5)')
    start_time = forms.CharField(label='Pick up time from hotel (e.g. 8am)')
    includes = forms.CharField(label='List what is included (e.g. Tuktuk '
                               'driver and guide, entrance fees, '
                               'mineral water etc.)')
    image_url = forms.URLField(label='Add the image URL here or upload the '
                               'image below (file should be 640 x 480px)',
                               required=False)
    image = forms.ImageField(label='Image', required=False,)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = '__all__'


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ('title', 'review_content',
                  'review_emoji', 'author',)

        placeholders = {
            'title': 'Give your review a short title',
            'review_content': 'Your Review',
            'review_emoji': 'Your Rating',
            'author': 'Your Name',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        ratings = Rating.objects.all()
        names = [(rating.id, rating.get_rating_name()) for rating in ratings]

        self.fields['review_emoji'].choices = names

tours/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.contrib import messages
from django.db.models import Q
from .models import Tour, Category
from blogs.models import BlogPost
from django.db.models.functions import Lower
from django.contrib.auth.decorators import login_required
from .forms import TourDetailForm, CategoryForm, ReviewForm


def all_tours(request):

    tours = Tour.objects.all()
    query = None
    categories = Category.objects.all()
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                tours = tours.annotate(lower_name=Lower('name'))
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            tours = tours.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            tours = tours.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "You didn't enter any search terms!")
                return redirect(reverse('tours'))

            queries = Q(name__icontains=query) | Q(description__icontains=query)
            tours = tours.filter(queries)

        if 'qt' in request.GET:
            query = request.GET['qt']
            if not query:
                messages.error(request, "You didn't enter any search terms!")
                return redirect(reverse('tours'))

            queries = Q(name__icontains=query) | Q(description__icontains=query)
            tours = tours.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'tours': tours,
        'categories': categories,
        'search_text': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'tours/tours.html', context)


def indv_tour(request, tour_id):
    """ A view to show individual tour details """

    tour = get_object_or_404(Tour, pk=tour_id)
    posts = BlogPost.objects.all()
    reviews = tour.reviews.all()

    context = {
        'tour': tour,
        'posts': posts,
        'reviews': reviews,
    }

    return render(request, 'tours/indv_tour.html', context)


@login_required
def make_review(request, tour_id):

    tour = get_object_or_404(Tour, pk=tour_id)
    review_form = ReviewForm

    context = {
        'tour': tour,
        'review_form': review_form,
    }

    return render(request, 'tours/indv_tour_add_review.html', context)


@login_required
def add_review(request, tour_id):
    """ A view to add a review to an individual tour """

    tour = get_object_or_404(Tour, pk=tour_id)
    new_review = None

    if request.method == 'POST':
        review_form = ReviewForm(request.POST, request.FILES)
        if review_form.is_valid():
            # Create Review object but don't save to database yet
            new_review = review_form.save(commit=False)
            # Assign the current review to the tour
            new_review.tour = tour
            # Save the review to the database
            new_review.save()
            messages.success(request, f'Thanks for reviewing the {tour.name}!')
            return redirect(reverse('indv_tour', args=[tour.id]))
    else:
        messages.error(request, 'Failed to add review. '
                       'Please ensure the form is valid.')
        review_form = ReviewForm()

    template = 'tours/indv_tour_add_review.html'
    context = {
        'tour': tour,
        'new_review': new_review,
        'review_form': review_form,
    }

    return render(request, template, context)


@login_required
def add_tour(request):
    """ Add a new tour to the site """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, you are not authorized to do that')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = TourDetailForm(request.POST, request.FILES)
        if form.is_valid():
            tour = form.save()
            messages.success(request, f'Successfully added the new \
                             tour {tour.name}!')
            return redirect(reverse('indv_tour', args=[tour.id]))
        else:
            messages.error(request, 'Failed to add new tour. '
                           'Please ensure the form is valid.')
    else:
        form = TourDetailForm()

    template = 'tours/add_tour.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_tour(request, tour_id):
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, you are not authorized to do that')
        return redirect(reverse('home'))

    tour = get_object_or_404(Tour, pk=tour_id)

    if request.method == 'POST':
        form = TourDetailForm(request.POST, request.FILES, instance=tour)
        if form.is_valid:
            form.save()
            messages.success(request, f'Successfully updated the {tour.name}')
            return redirect(reverse('indv_tour', args=[tour.id]))
        else:
            messages.error(request, 'Failed to update tour. '
                           'Check that the form entry is valid')
    else:
        form = TourDetailForm(instance=tour)
        messages.info(request, f'You are editing the {tour.name}')

    template = 'tours/edit_tour.html'
    context = {
        'form': form,
        'tour': tour,
    }

    return render(request, template, context)


@login_required
def delete_tour(request, tour_id):
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, you are not authorized to do that')
        return redirect(reverse('home'))

    tour = get_object_or_404(Tour, pk=tour_id)
    tour.delete()
    messages.success(request, f'Deleted the {tour.name}')
    return redirect(reverse('tours'))


def all_categories(request):

    categories = Category.objects.all()

    context = {
        'categories': categories,
    }

    return render(request, 'tours/categories.html', context)


@login_required
def add_category(request):
    """ Add a new category to the site """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, you are not authorized to do that')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            category = form.save()
            messages.success(request, f'Successfully added new category \
                             { category.friendly_name }!')
            return redirect(reverse('categories'))
        else:
            messages.error(request, 'Failed to add new category. '
                           'Please ensure the form is valid.')
    else:
        form = CategoryForm()

    template = 'tours/categories/add_category.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_category(request, category_id):
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, you are not authorized to do that')
        return redirect(reverse('home'))

    category = get_object_or_404(Category, pk=category_id)

    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES, instance=category)
        if form.is_valid:
            form.save()
            messages.success(request, f'Successfully updated category \
                             { category.friendly_name }')
            return redirect(reverse('categories'))
        else:
            messages.error(request, 'Failed to update category. '
                           'Check that the form entry is valid')
    else:
        form = CategoryForm(instance=category)
        messages.info(request, f'You are editing the category \
                      {category.friendly_name}')

    template = 'tours/categories/edit_category.html'
    context = {
        'form': form,
        'category': category,
    }

    return render(request, template, context)


@login_required
def delete_category(request, category_id):
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, you are not authorized to do that')
        return redirect(reverse('home'))

    category = get_object_or_404(Category, pk=category_id)
    category.delete()
    messages.success(request, f'Deleted the category {category.friendly_name}')
    return redirect(reverse('categories'))

tours/templates/tours/add_tour.html
{% extends "base.html" %} {% load static %} {% load materializecss %}
{% block extra_css %}
{% endblock %}
{% block page_header %}
<div class="row">
    <div class="col s12 valign-wrapper subheading">
        <h4>Add New Tour</h4>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="row">
    <form action="{% url 'add_tour' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
            <div class="card-panel add-tour">
                {% for field in form %}
                {% if field.name != 'image' %}
                {{ field | materializecss }}
                {% else %}
                <span>
                    <input id="new_image" type="file" name="image" accept="image/*">
                </span>
                <p class="grey-text text-darken-3 bold" id="filename"></p><br />
                {% endif %}
                {% endfor %}
                <div class="submit-button center-align">
                    <a href="{% url 'tours' %}"
                        class="waves-effect waves-light btn rounded-4 text-uppercase sm-blue-button">
                        <span class="icon">
                            <i class="fas fa-chevron-left"></i>
                        </span>
                        <span>Cancel</span>
                    </a>
                    <button id="submit-button"
                        class="waves-effect waves-light btn rounded-4 text-uppercase sm-blue-button">
                        <span>Add New Tour</span>
                        <span class="icon">
                            <i class="fas fa-plus"></i>
                        </span>
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script>
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    })
</script>
<script>
    $('#id_description').val('');
  M.textareaAutoResize($('#id_description'));
</script>
{% endblock %}

tours/templates/tours/categories.html
{% extends "base.html" %} {% load static %}
{% block page_header %}
<div class="row">
    <div class="col s12 valign-wrapper subheading">
        <h4>Categories</h4>
    </div>
</div>
{% endblock %}
{% block content %}
{% if request.user.is_superuser %}
<div class="container center-align">
    <a href="{% url 'add_category' %}" class="waves-effect waves-light btn rounded-4 text-uppercase sm-blue-button">
        Add New Category<i class="fas fa-plus"></i></a>
</div>
{% endif %}
<div class="row">
    {% for category in categories %}
    <div class="col s12 m3">
        <div class="card white center-align">
            <div class="card-content black card-padding">
                <h4>{{ category.friendly_name }}</h4>
            </div>
            <div class="shadowed card-action">
                <a href="{% url 'edit_category' category.id %}"
                    class="waves-effect waves-light btn rounded-4 text-uppercase sm-blue-button wt-shadow">Edit Category<i
                        class="fas fa-pencil-alt"></i></a>
                <a href="{% url 'delete_category' category.id %}"
                    class="waves-effect waves-light btn rounded-4 text-uppercase sm-blue-button wt-shadow">Delete
                    Category<i class="fas fa-pencil-alt"></i></a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="btt-link">
    <a class="waves-effect waves-light btn rounded-4 text-uppercase btt">
        <i class="fas fa-arrow-up"></i>
    </a>
</div>
{% endblock %}
{% block postloadjs %}
{{ block.super }}
<script>
    $('.back-to-top').click(function (e) {
        window.scrollTo(0, 0)
    })
</script>
{% endblock %}

tours/templates/tours/edit_tour.html
{% extends "base.html" %} {% load static %} {% load materializecss %}
{% block extra_css %}
{% endblock %}
{% block page_header %}
<div class="row">
    <div class="col s12 valign-wrapper subheading">
        <h4>Edit Tour</h4>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="row">
    <form action="{% url 'edit_tour' tour.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
            <div class="card-panel add-tour">
                {% for field in form %}
                {% if field.name != 'image' %}
                {{ field | materializecss }}
                {% else %}
                <p>Current image:</p>
                {% if tour.image %}
                    <a class="edit-image" href="{% url 'indv_tour' tour.id %}">
                        <img src="{{ tour.image.url }}" alt="{{ tour.name }}" />
                    </a><br/>
                    {% else %}
                    <a class="edit-image" href="{% url 'indv_tour' tour.id %}">
                        <img src="{{ MEDIA_URL }}noimage.png" alt="{{ tour.name }}" />
                    </a><br/>
                    {% endif %}
                <span>
                    <input id="new_image" type="file" name="image" accept="image/*">
                </span>
                <p class="grey-text text-darken-3 bold" id="filename"></p><br />
                {% endif %}
                {% endfor %}
                <div class="submit-button center-align">
                    <a href="{% url 'tours' %}"
                        class="waves-effect waves-light btn rounded-4 text-uppercase sm-blue-button">
                        <span class="icon">
                            <i class="fas fa-chevron-left"></i>
                        </span>
                        <span>Cancel</span>
                    </a>
                    <button id="submit-button"
                        class="waves-effect waves-light btn rounded-4 text-uppercase sm-blue-button">
                        <span>Update Tour</span>
                        <span class="icon">
                            <i class="fas fa-check"></i>
                        </span>
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script>
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    })
</script>
<script>
    $('#id_description').val(`${tour.description}`);
  M.textareaAutoResize($('#id_descrition'));
</script>
{% endblock %}

tours/templates/tours/indv_tour_add_review.html
{% extends "base.html" %} {% load static %} {% load materializecss %}
{% block page_header %}
<div class="row">
    <div class="col s12 valign-wrapper subheading">
        <h4>Leave a review for {{ tour.name }}</h4>
    </div>
</div>
{% endblock %}
{% block content %}
{% if request.user.is_authenticated %}
<div class="card-body">
    <form action="{% url 'add_review' tour.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
            <div class="card-panel add-tour">
                {{ review_form | materializecss }}
                <div class="submit-button center-align">
                    <a href="{% url 'indv_tour' tour.id %}"
                        class="waves-effect waves-light btn rounded-4 text-uppercase sm-blue-button">
                        <span class="icon">
                            <i class="fas fa-chevron-left"></i>
                        </span>
                        <span>Cancel</span>
                    </a>
                <button id="submit-button" class="waves-effect waves-light btn rounded-4 text-uppercase sm-blue-button">
                    <span>Publish Review</span>
                    <span class="icon">
                        <i class="fas fa-plus"></i>
                    </span>
                </button>
            </div>
            </div>
        </div>
    </form>
</div>
{% endif %}
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% endblock %}

tours/templates/tours/tours.html
{% extends "base.html" %} {% load static %}
{% block page_header %}
<div class="row">
    <div class="col s12 valign-wrapper subheading">
        <h4>Tours</h4>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col s12 center-align">
        {% for c in categories %}
            <a href="{% url 'tours' %}?category={{ c.name }}" class="waves-effect waves-light btn rounded-4 text-uppercase sm-blue-button">
                <span>{{ c.friendly_name }}</span>
            </a>
        {% endfor %}
    </div>
</div>
<div class="row">
    <form method="GET" action="{% url 'tours' %}" class="col s12 m6">
            <div class="input-field col s10 post-search">
                <input type="text" id="qt" name="qt" minlength="3" class="validate" />
                <label for="qt">Search Posts</label>
            </div>
            <div class="col s2 left-align">
                <button class="btn tuktuk-blue search-btn" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </form>
<div class="input-field col s12 m5 l5">
    <select id="sort-selector">
        <option value="" disabled selected>Sort Tours</option>
        <option value="reset" {% if current_sorting == 'None_None' %}selected{% endif %}>Sort by ...</option>
        <option value="price_asc" {% if current_sorting == 'price_asc' %}selected{% endif %}>Price (low to high)
        </option>
        <option value="price_desc" {% if current_sorting == 'price_desc' %}selected{% endif %}>Price (high to low)
        </option>
        <option value="rating_asc" {% if current_sorting == 'rating_asc' %}selected{% endif %}>Rating (low to high)
        </option>
        <option value="rating_desc" {% if current_sorting == 'rating_desc' %}selected{% endif %}>Rating (high to low)
        </option>
    </select>
    <label></label>
</div>
</div>
<div class="col s12 search-result count">
    <p>
        {% if search_text or current_categories or current_sorting != 'None_None' %}
        <span><a href="{% url 'tours' %}">All Tours</a> | </span>
        {% endif %}
        {{ tours|length }} {% if tours|length == 1 %}Tour{% else%}Tours{% endif %}{% if search_text %} found for
        <strong>"{{ search_text }}"</strong>{% endif %}
    </p>
</div>
<div class="row">
    {% for tour in tours %}
    <div class="col s12 m4 l3">
        <div class="card">
            <div class="card-image">
                {% if tour.image %}
                <a href="{% url 'indv_tour' tour.id %}">
                    <img src="{{ tour.image.url }}" alt="{{ tour.name }}" />
                </a>
                {% else %}
                <a href="{% url 'indv_tour' tour.id %}">
                    <img src="{{ MEDIA_URL }}noimage.png" alt="{{ tour.name }}" />
                </a>
                {% endif %}
            </div>
            <div class="black center-align">
                <h5>{% if tour.category.friendly_name %}{{ tour.category.friendly_name }}{% else %}Tuk Tuk Tours{% endif %}</h5>
            </div>
            <div class="card-content tour-card-desc">
                <p class="tour-description">{{ tour.description|slice:":200" }}</p>
            </div>
            <div class="card-content tour-card-name tuktuk-blue white-text uppercase">
                <a href="{% url 'indv_tour' tour.id %}">
                    <span id="tour-card-name">{{ tour.name }}  <i class="fas fa-arrow-right"></i></span>
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="btt-link">
    <a class="waves-effect waves-light btn rounded-4 text-uppercase btt">
        <i class="fas fa-arrow-up"></i>
    </a>
</div>
{% endblock %}
{% block postloadjs %}
{{ block.super }}
<script>
    $('.btt-link').click(function (e) {
        window.scrollTo(0, 0)
    })
</script>
<script>
    $('#sort-selector').change(function () {
        var selector = $(this);
        var currentURL = new URL(window.location);

        var selectedVal = selector.val();
        if (selectedVal != "reset") {
            var sort = selectedVal.split("_")[0];
            var direction = selectedVal.split("_")[1];

            currentURL.searchParams.set("sort", sort);
            currentURL.searchParams.set("direction", direction);

            window.location.replace(currentURL);
        } else {
            currentURL.searchParams.delete("sort");
            currentURL.searchParams.delete("direction");

            window.location.replace(currentURL);
        }
    })
</script>
{% endblock %}